[workspace]
members = [
    "projects/chat/server",
    "projects/shortener",
    "projects/tmanager",
    "projects/image",
    "projects/compression",
    "projects/crusty",
    "projects/neuralnetwork"
]